apiVersion: v1
kind: ConfigMap
metadata:
  name: payroll-api-config
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_HTTP_PORTS: "3000"
  Database__EnsureCreated: "false"
  Jwt__Issuer: PayrollApi
  Jwt__Audience: PayrollReactApp
